export const transitionDuration: string;
export const rtlEnter: string;
export const rtlEnterActive: string;
export const rtlExit: string;
export const rtlExitActive: string;
export const ltrEnter: string;
export const ltrEnterActive: string;
export const ltrExit: string;
export const ltrExitActive: string;
